### ISSUE TITLE
What version NodeJS and NPM NyaaCat using?

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/NyaaStats#8]
I'm trying install NyaaStats on CentOS server, but it throwed error.

https://paste.ubuntu.com/p/BYt4M7bGd2/

I think maybe is my NodeJS/NPM version issue.

```
[root@localhost NyaaStats]# npm -v
6.9.0
[root@localhost NyaaStats]# node -v
v12.3.1
```

**Comment by Ghost-chu** [comment]
I switch the NodeJS and NPM version.

Failed on npm install

```
[root@localhost NyaaStats]# npm start

> nyaa-stats@0.0.1 start /root/NyaaStats
> babel-node -- index.js

/root/NyaaStats/index.js:60
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at loader (/root/NyaaStats/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/NyaaStats/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Function.Module.runMain (module.js:611:10)
    at Object.<anonymous> (/root/NyaaStats/node_modules/babel-cli/lib/_babel-node.js:154:22)

npm ERR! Linux 3.10.0-957.12.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! nyaa-stats@0.0.1 start: `babel-node -- index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nyaa-stats@0.0.1 start script 'babel-node -- index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nyaa-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node -- index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nyaa-stats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nyaa-stats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/NyaaStats/npm-debug.log
[root@localhost NyaaStats]#
```
